import { Deal } from '../entities/deal.entity';

/**
 * Sample deals data for testing and development
 * 
 * These deals demonstrate various categories, price ranges,
 * and deal types (hot, featured, regular)
 */
export const sampleDeals: Partial<Deal>[] = [
  // Electronics
  {
    title: 'Apple AirPods Pro (2nd Generation) - USB-C',
    description: 'Active Noise Cancellation, Personalized Spatial Audio, MagSafe Charging Case. Amazing sound quality with H2 chip.',
    price: 189.99,
    originalPrice: 249.00,
    imageUrl: 'https://m.media-amazon.com/images/I/61SUj2aKoEL._AC_SL1500_.jpg',
    affiliateLink: 'https://www.amazon.com/dp/B0CHWRXH8B',
    category: 'Electronics',
    isHot: true,
    isFeatured: true,
    expiryDate: new Date('2026-02-15'),
  },
  {
    title: 'Samsung 65" Class OLED 4K Smart TV',
    description: 'Quantum HDR OLED, Neural Quantum Processor, Object Tracking Sound. Stunning picture quality for movies and gaming.',
    price: 1497.99,
    originalPrice: 2299.99,
    imageUrl: 'https://m.media-amazon.com/images/I/71RiQZ0J2mL._AC_SL1500_.jpg',
    affiliateLink: 'https://www.amazon.com/dp/B0BV1VWKZB',
    category: 'Electronics',
    isHot: true,
    isFeatured: false,
    expiryDate: new Date('2026-01-31'),
  },
  {
    title: 'Sony WH-1000XM5 Wireless Headphones',
    description: 'Industry Leading Noise Cancellation, 30-Hour Battery Life, Crystal Clear Calls. The best headphones for travel.',
    price: 278.00,
    originalPrice: 399.99,
    imageUrl: 'https://m.media-amazon.com/images/I/61vJtKbIPoL._AC_SL1500_.jpg',
    affiliateLink: 'https://www.amazon.com/dp/B09XS7JWHH',
    category: 'Electronics',
    isHot: false,
    isFeatured: true,
    expiryDate: new Date('2026-02-28'),
  },

  // Home & Kitchen
  {
    title: 'Ninja Foodi 9-in-1 Pressure Cooker & Air Fryer',
    description: 'TenderCrisp Technology, 6.5-Quart Capacity, Pressure Cook, Air Fry, Steam, Slow Cook. Perfect for busy families.',
    price: 129.99,
    originalPrice: 229.99,
    imageUrl: 'https://m.media-amazon.com/images/I/81GsUDmxWLL._AC_SL1500_.jpg',
    affiliateLink: 'https://www.amazon.com/dp/B07S85TPLG',
    category: 'Home & Kitchen',
    isHot: true,
    isFeatured: true,
    expiryDate: new Date('2026-01-20'),
  },
  {
    title: 'Dyson V15 Detect Cordless Vacuum',
    description: 'Laser reveals microscopic dust, LCD screen shows proof of deep clean, up to 60 minutes of run time.',
    price: 549.99,
    originalPrice: 749.99,
    imageUrl: 'https://m.media-amazon.com/images/I/61whFODqMiL._AC_SL1500_.jpg',
    affiliateLink: 'https://www.amazon.com/dp/B0977PS6RQ',
    category: 'Home & Kitchen',
    isHot: false,
    isFeatured: true,
    expiryDate: new Date('2026-02-10'),
  },
  {
    title: 'Keurig K-Supreme Plus Coffee Maker',
    description: 'MultiStream Technology, Programmable, Over Ice Setting, 78oz Removable Reservoir. Brew your perfect cup.',
    price: 99.99,
    originalPrice: 169.99,
    imageUrl: 'https://m.media-amazon.com/images/I/71RiYWLVkJL._AC_SL1500_.jpg',
    affiliateLink: 'https://www.amazon.com/dp/B08F4PSQHV',
    category: 'Home & Kitchen',
    isHot: true,
    isFeatured: false,
    expiryDate: new Date('2026-01-25'),
  },

  // Fashion
  {
    title: 'Levi\'s Men\'s 501 Original Fit Jeans',
    description: 'Classic straight leg, button fly, 100% cotton. The original blue jean since 1873.',
    price: 34.99,
    originalPrice: 69.50,
    imageUrl: 'https://m.media-amazon.com/images/I/61UfyyYMwzL._AC_SL1500_.jpg',
    affiliateLink: 'https://www.amazon.com/dp/B0018OLTAC',
    category: 'Fashion',
    isHot: true,
    isFeatured: false,
    expiryDate: new Date('2026-02-01'),
  },
  {
    title: 'Nike Air Max 270 Men\'s Running Shoes',
    description: 'Max Air unit for cushioning, mesh upper for breathability, rubber outsole. Comfort meets style.',
    price: 89.97,
    originalPrice: 150.00,
    imageUrl: 'https://m.media-amazon.com/images/I/71pr8jj-qXL._AC_SL1500_.jpg',
    affiliateLink: 'https://www.amazon.com/dp/B078NKSHQZ',
    category: 'Fashion',
    isHot: false,
    isFeatured: true,
    expiryDate: new Date('2026-01-30'),
  },

  // Sports & Outdoors
  {
    title: 'YETI Rambler 36 oz Bottle with Chug Cap',
    description: 'Double-wall vacuum insulation, 18/8 stainless steel, dishwasher safe. Keeps drinks cold for 24+ hours.',
    price: 38.00,
    originalPrice: 50.00,
    imageUrl: 'https://m.media-amazon.com/images/I/51p3u0T7h2L._AC_SL1500_.jpg',
    affiliateLink: 'https://www.amazon.com/dp/B073WJ36Q4',
    category: 'Sports & Outdoors',
    isHot: false,
    isFeatured: false,
    expiryDate: new Date('2026-03-15'),
  },
  {
    title: 'Fitbit Charge 6 Fitness Tracker',
    description: 'Built-in GPS, 24/7 Heart Rate, Sleep Tracking, 7-day battery, Google apps integration.',
    price: 119.95,
    originalPrice: 159.95,
    imageUrl: 'https://m.media-amazon.com/images/I/61owT94+WqL._AC_SL1500_.jpg',
    affiliateLink: 'https://www.amazon.com/dp/B0CC62F31R',
    category: 'Sports & Outdoors',
    isHot: true,
    isFeatured: true,
    expiryDate: new Date('2026-02-20'),
  },

  // Books
  {
    title: 'Atomic Habits by James Clear (Hardcover)',
    description: 'An Easy & Proven Way to Build Good Habits & Break Bad Ones. #1 New York Times Bestseller.',
    price: 13.79,
    originalPrice: 27.00,
    imageUrl: 'https://m.media-amazon.com/images/I/81wgcld4wxL._AC_SL1500_.jpg',
    affiliateLink: 'https://www.amazon.com/dp/0735211299',
    category: 'Books',
    isHot: false,
    isFeatured: true,
    expiryDate: null,
  },
  {
    title: 'Kindle Paperwhite (16 GB) - 6.8" Display',
    description: 'Adjustable warm light, 10 weeks of battery life, waterproof. Read anywhere, anytime.',
    price: 109.99,
    originalPrice: 149.99,
    imageUrl: 'https://m.media-amazon.com/images/I/61PnLJrlPxL._AC_SL1000_.jpg',
    affiliateLink: 'https://www.amazon.com/dp/B09TMN58KL',
    category: 'Electronics',
    isHot: true,
    isFeatured: false,
    expiryDate: new Date('2026-01-28'),
  },

  // Gaming
  {
    title: 'PlayStation 5 DualSense Wireless Controller',
    description: 'Haptic feedback, adaptive triggers, built-in microphone. Feel every action in your hands.',
    price: 49.00,
    originalPrice: 74.99,
    imageUrl: 'https://m.media-amazon.com/images/I/619jLsevRrL._SL1500_.jpg',
    affiliateLink: 'https://www.amazon.com/dp/B08FC6C75Y',
    category: 'Gaming',
    isHot: true,
    isFeatured: true,
    expiryDate: new Date('2026-02-05'),
  },
  {
    title: 'Nintendo Switch OLED Model - White',
    description: '7-inch OLED screen, wide adjustable stand, dock with wired LAN port. Play at home or on-the-go.',
    price: 299.00,
    originalPrice: 349.99,
    imageUrl: 'https://m.media-amazon.com/images/I/61DcCeq7-kL._SL1500_.jpg',
    affiliateLink: 'https://www.amazon.com/dp/B098RKWHHZ',
    category: 'Gaming',
    isHot: false,
    isFeatured: true,
    expiryDate: new Date('2026-02-14'),
  },

  // Beauty
  {
    title: 'Revlon One-Step Volumizer Hair Dryer',
    description: 'Unique oval brush design, ionic technology, multiple heat settings. Salon-quality blowout at home.',
    price: 29.99,
    originalPrice: 59.99,
    imageUrl: 'https://m.media-amazon.com/images/I/71KUQG+GYLL._SL1500_.jpg',
    affiliateLink: 'https://www.amazon.com/dp/B01LSUQSB0',
    category: 'Beauty',
    isHot: true,
    isFeatured: false,
    expiryDate: new Date('2026-01-22'),
  },
];
